CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR2(100 BYTE) NOT NULL,
    apellido   VARCHAR2(100 BYTE) NOT NULL,
    telefono   VARCHAR2(15 BYTE)  NOT NULL,
    email      VARCHAR2(100 BYTE) NOT NULL,
    direccion  VARCHAR2(200 BYTE) DEFAULT 'SIN ESPECIFICAR' NOT NULL,

    CONSTRAINT clientes_pk PRIMARY KEY (id_cliente),
    CONSTRAINT clientes_email_uk UNIQUE (email),
    CONSTRAINT clientes_nombre_ck CHECK (TRIM(nombre) IS NOT NULL),
    CONSTRAINT clientes_apellido_ck CHECK (TRIM(apellido) IS NOT NULL),
    CONSTRAINT clientes_telefono_ck CHECK
        (REGEXP_LIKE(telefono, '^[0-9+() -]{7,15}$')),
    CONSTRAINT clientes_email_ck CHECK
        (REGEXP_LIKE(email, '^[[:alnum:]._%+-]+@[[:alnum:].-]+\.[[:alpha:]]{2,}$')),
    CONSTRAINT clientes_direccion_ck CHECK (TRIM(direccion) IS NOT NULL)
);

CREATE TABLE salones (
    id_salon     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_salon VARCHAR2(100 BYTE) NOT NULL,
    capacidad    NUMBER DEFAULT 1 NOT NULL,
    precio_renta NUMBER(10,2) DEFAULT 0 NOT NULL,
    ubicacion    VARCHAR2(100 BYTE) DEFAULT 'SIN ESPECIFICAR' NOT NULL,

    CONSTRAINT salones_pk PRIMARY KEY (id_salon),
    CONSTRAINT salones_nombre_uk UNIQUE (nombre_salon),
    CONSTRAINT salones_nombre_ck CHECK (TRIM(nombre_salon) IS NOT NULL),
    CONSTRAINT salones_capacidad_ck CHECK (capacidad > 0),
    CONSTRAINT salones_precio_ck CHECK (precio_renta >= 0),
    CONSTRAINT salones_ubicacion_ck CHECK (TRIM(ubicacion) IS NOT NULL)
);

CREATE TABLE eventos (
    id_evento       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      NUMBER NOT NULL,
    id_salon        NUMBER NOT NULL,
    nombre_evento   VARCHAR2(100 BYTE) NOT NULL,
    fecha_evento    DATE DEFAULT SYSDATE NOT NULL,
    cantidad_personas NUMBER DEFAULT 1 NOT NULL,
    cantidad_horas  NUMBER DEFAULT 1 NOT NULL,
    estado          VARCHAR2(20 BYTE) DEFAULT 'PENDIENTE' NOT NULL,
    total_pago      NUMBER(8,2) DEFAULT 0 NOT NULL,

    CONSTRAINT eventos_pk PRIMARY KEY (id_evento),
    CONSTRAINT eventos_cliente_nombre_fecha_uk
        UNIQUE (id_cliente, nombre_evento, fecha_evento),
    CONSTRAINT eventos_nombre_ck CHECK (TRIM(nombre_evento) IS NOT NULL),
    CONSTRAINT eventos_personas_ck CHECK (cantidad_personas > 0),
    CONSTRAINT eventos_horas_ck CHECK (cantidad_horas BETWEEN 1 AND 24),
    CONSTRAINT eventos_estado_ck
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADO', 'CANCELADO', 'FINALIZADO')),
    CONSTRAINT eventos_pago_ck CHECK (total_pago >= 0),
    CONSTRAINT fk_eventos_clientes FOREIGN KEY (id_cliente)
        REFERENCES clientes (id_cliente),
    CONSTRAINT fk_eventos_salones FOREIGN KEY (id_salon)
        REFERENCES salones (id_salon)
);

-- Índices para las claves foráneas; mejoran consultas y operaciones padre-hijo.
CREATE INDEX eventos_cliente_ix ON eventos (id_cliente);
CREATE INDEX eventos_salon_ix ON eventos (id_salon);

INSERT INTO clientes values ('Tania', 'Ramirez', '1324-9878', 'RUMI@GMAIL.COM', 'MI CASA');

select *from clientes;
